"""stufsf

Revision ID: df592db974d2
Revises: 95492db630fe
Create Date: 2021-06-24 00:06:39.661652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df592db974d2'
down_revision = '95492db630fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('seats', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'seats')
    # ### end Alembic commands ###
